# **Tarea 4 - CC6205 Natural Language Processing 📚**

**Integrantes:**

**Fecha límite de entrega 📆:** Martes 22 de junio.

**Tiempo estimado de dedicación:**

Bienvenid@s a la cuarta tarea del curso de Natural Language Processing (NLP). 
En esta tarea estaremos tratando el problema de **tagging** (generación de secuencias de etiquetas del mismo largo que la secuencia de input), el uso de **Convolutional Neural Networks** y **Recurrent Neural Networks**, e implementaremos una red usando PyTorch. 

Usen $\LaTeX$ para las fórmulas matemáticas. En la parte de programación pueden usar lo que quieran, pero la [Axiliar 3](https://www.youtube.com/watch?v=r1pt9v_vuy8&list=PLwITEwTGVF6jXRu6l55W4OedqDiLgU9OM&index=2&t=5s) les puede ser de *gran ayuda*.

**Instrucciones:**
- La tarea se realiza en grupos de **máximo** 2 personas. Puede ser invidivual pero no es recomendable.
- La entrega es a través de u-cursos a más tardar el día estipulado arriba. No se aceptan atrasos.
- El formato de entrega es este mismo Jupyter Notebook.
- Al momento de la revisión tu código será ejecutado. Por favor verifica que tu entrega no tenga errores de compilación.
- En el horario de auxiliar pueden realizar consultas acerca de la tarea a través del canal de Discord del curso.

Si aún no han visto las clases, se recomienda visitar los links de las referencias.

**Referencias:**

- [Tagging, and Hidden Markov Models ](http://www.cs.columbia.edu/~mcollins/cs4705-spring2019/slides/tagging.pdf) (slides by Michael Collins), [notes](http://www.cs.columbia.edu/~mcollins/hmms-spring2013.pdf), [video 1](https://youtu.be/-ngfOZz8yK0), [video 2](https://youtu.be/Tjgb-yQOg54), [video 3](https://youtu.be/aaa5Qoi8Vco), [video 4](https://youtu.be/4pKWIDkF_6Y)       
- [MEMMs and CRFs](slides/NLP-CRF.pdf) | ([tex source file](slides/NLP-CRF.tex)), [notes 1](http://www.cs.columbia.edu/~mcollins/crf.pdf), [notes 2](http://www.cs.columbia.edu/~mcollins/fb.pdf), [video 1](https://youtu.be/qlI-4lSUDkg), [video 2](https://youtu.be/PLoLKQwkONw), [video 3](https://youtu.be/ZpUwDy6o28Y)
- [Convolutional Neural Networks](slides/NLP-CNN.pdf) | ([tex source file](slides/NLP-CNN.tex)), [video](https://youtu.be/lLZW5Fn40r8)
- [Recurrent Neural Networks](slides/NLP-RNN.pdf) | ([tex source file](slides/NLP-RNN.tex)), [video 1](https://youtu.be/BmhjUkzz3nk), [video 2](https://youtu.be/z43YFR1iIvk), [video 3](https://youtu.be/7L5JxQdwNJk)

# Hidden Markov Models (HMM), Maximum Entropy Markov Models (MEMM) and Conditional Random Field(CRF)

### Pregunta 1 (1 pt)
Para un problema de POS tagging se define el conjunto de etiquetas $S = \{ \text{DET}, \text{NOUN}, \text{VERB}, \text{ADP} \}$ y se tiene un Hidden Markov Model con los siguientes parámetros estimados a partir de un corpus de entrenamiento:

\begin{equation}
\begin{split}
q(\text{NOUN}| \text{ VERB}, \text{DET}) &= 0.3 \\
q(\text{NOUN}|\ w, \text{DET}) &= 0 \qquad \forall w \in S, w \neq \text{VERB} \\
q(\text{DET}| \text{ VERB}, \text{NOUN}) &= 0.4 \\
q(\text{DET}|\ w, \text{NOUN}) &= 0 \qquad \forall w \in S, w \neq \text{VERB} \\
e(the|\text{ DET}) &= 0.5 \\
e(pasta|\text{ NOUN}) &= 0.6
\end{split}
\end{equation}

Luego para la oración: `the man is pouring sauce on the pasta`, se tiene una tabla de programación dinámica con los siguientes valores:
\begin{equation}
\begin{split}
\pi(7,\text{DET},\text{DET})&=0.1\\
\pi(7,\text{NOUN},\text{DET})&=0.2\\
\pi(7,\text{VERB},\text{DET})&=0.01\\
\pi(7,\text{ADP},\text{DET})&=0.5
\end{split}
\end{equation}

Con esta información, calcule el valor de $\pi(8,\text{DET},\text{NOUN})$. Puede dejar el resultado expresado como una fracción.


**Respuesta**
\begin{equation}
\begin{split}
\pi(8,\text{DET},\text{NOUN}) &= \max_{w\in S_{6}} \big(\pi(7, w, \text{DET}) \times q(\text{NOUN}|w,\text{DET}) \times e(\text{pasta}|\text{NOUN})\big)\\ 
&= \pi(7, \text{VERB}, \text{DET}) \times q(\text{NOUN}|\text{VERB},\text{DET}) \times e(\text{pasta}|\text{NOUN})\\
&= 0.01 \times 0.3 \times 0.6 \\
&= 0.0018
\end{split}
\end{equation}


### Pregunta 2 (0.5 pts)
Comente  sobre las similitudes o diferencias entre los HMMs, MEMMs y CRFs. Para esto, responda las siguientes preguntas.

#### 2.1. ¿Para qué tipo de tarea sirven? Dé dos ejemplo de este tipo de tarea y descríbalos brevemente. (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.2. ¿Qué modelos usan features? ¿Qué ventajas conlleva esto? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.3. ¿Cómo maneja cada uno de los modelos las palabras con baja frecuencia en el set de train? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.4. ¿Qué le permite a los CRF realizar decisiones globales? ¿Qué diferencia con respecto a los MEMMs permite lograr esto? ¿Por qué los HMMs tampoco son capaces de tomar decisiones globales? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.5 Dado una secuencia de $x_1, ..., x_m$ ¿Cuántas posibles secuencias de etiquetas se pueden generar para un conjunto de etiquetas $S$ con $|S|=k$ ? ¿Analizarlas todas sería computacionalmente tratable? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

**Respuestas**
#### Problemas para los que sirven:
Problemas que producen como salida una secuencia de etiquetas, a partir de una secuencia de entrada. Estos problemas con conocidos como *sequence labeling* y dos ejemplos de problemas de este tipo son:
- Named Entity Recognition (NER): Tiene como objetivo localizar y clasificar en categorías predefinidas, como personas, organizaciones, lugares, expresiones de tiempo y cantidades, las entidades encontradas en el texto de input.
- Part-of-Speech (POS) Tagging: El objetivo es generar un secuencia de etiquetas que representan la categoría gramatical de cada una de las palabras del texto de input.

#### Modelos que usan features, ventajas:
Los modelos que usan features son MEMMs y CRF. Son modelos discriminativos mientras que los HMMs son modelos generativos. Los modelos discriminativos modelan directamente la probabilidad condicional utilizando un modelo parametrizado, minetras que los generativos utilizan solo la probabilidad conjunta.

#### Manejo de las palabras con baja frecuencia:
En lose HMMs se reemplazan las palabras poco frecuentes por categorías. Para esto, se divide el vocabulario en dos subconjuntos mediante un umbral de frecuencia: uno con las palabras frecuentes y otro con las poco frecuentes. Luego se convierten las poco frecuentes a un conjunto fijo de categorías, por ejemplo, las fechas, los numeros y los nombres.
En la fase de testing, las palabras desconocidas las podemos llevar a estas categorias en vez de solo usar el token **unk**.
Esto trae como ventaja una mejora en las propiedades de generalizacion del modelo.

En los MEMMs lo que tenemos son funciones parametrizadas para los cuales se aprenden pesos. Dado esto, el input se trata como un vector de caracteristicas (features). 
Los inputs de los MEMMs incluyen la etiqueta. Esto tiene como ventaja que perimite codificar relaciones más directas entre la etiqueta y el input. 
Estas relaciones se determinan mediante el uso de $\phi(\cdot, \cdot)$

#### Decisiones globales de los CRFs, diferencias con respecto a los HMMs y MEMMs:
En los CRFs la normalización es global, mientras que en los MEMMs la normalización en local. Esto hace que entrenar una MEMMs es menos complicado que entrenar los CRFs.

La gran ventaja de CRFs sobre MEMMs es que puede resolver un problema que se llama label bias. Este problema se da porque para algunas configuraciones de las etiquetas las MEMMs pueden ignorar informacion importante del contexto al realizar decisiones independientes en cada paso. Esto puede probocar una asignación erronea de la etiqueta.

# Convolutional Neural Networks
### Pregunta 3 (1 pt)

Considere la frase $w_{1..7}=$ `El agua moja y el fuego quema` $=[El, agua, moja, y, el, fuego, quema]$.

La siguiente matriz de embeddings, donde la i-ésima fila corresponde al vector de embedding de la i-ésima palabra, ordenadas según aparecen en la frase. (vectores de largo 2).
\begin{equation}
E = \begin{pmatrix}
2 & 2\\
0 & -2\\
0 & 1\\
-2 & 1\\
1 & 0\\
-1 & 1\\
1 & 1
\end{pmatrix}
\end{equation}

Los siguientes 3 filtros
\begin{equation}
U = \begin{pmatrix}
-1 & 1 & 0\\
1 & 1 & 0\\
0 & 0 & -1\\
1 & -1 & -1\\
-1 & -1 & 1\\
1 & 0 & -1
\end{pmatrix}
\end{equation}

Y la función de activación
\begin{equation}
tanh = \frac{e^{2x} - 1}{e^{2x} + 1}
\end{equation}

Usando estos paramátros escriba los pasos para calcular la representación (vector) resultante de aplicar la operación de convolución (sin padding) + max pooling. ¿De qué tamaño sería la ventana que debemos usar?

**Respuesta**
Dado que la matriz de filtro tiene 6 filas y los embedigs son vectores de largo 2, concluimos que la ventana es de tamaño 3. Por tanto estamos usando n-gramas de 3 palabras.

\begin{equation}
\begin{split}
w_{1..3} &=[El, agua, moja] &= \big(2,2,0,-2,0,1\big)\\
w_{2..4} &=[agua, moja, y]  &= \big(0,-2,0,1,-2,1\big)\\
w_{3..5} &=[moja, y, el]    &= \big(0,1,-2,1,1,0\big)\\
w_{4..6} &=[y, el, fuego]   &= \big(-2,1,1,0,-1,1\big)\\
w_{5..7} &=[el, fuego, quema] &= \big(1,0,-1,1,1,1\big)\\
\end{split}
\end{equation}

\

\begin{equation}
\begin{split}
[[-1  6  1]
 [ 2 -1 -4]
 [ 1 -1  2]
 [ 5  0 -3]
 [ 0 -1  0]]
u_{1..3} &=\text{tanh}(w_{1..3} \cdot U) &= \text{tanh}\big((-1,6,1)\big)&=(-0.76159416&,  0.99998771&,  0.76159416&)\\
u_{2..4} &=\text{tanh}(w_{2..4} \cdot U) &= \text{tanh}\big((1,-1,-4)\big)&=(0.96402758&, -0.76159416&, -0.9993293&)\\
u_{3..5} &=\text{tanh}(w_{3..5} \cdot U) &= \text{tanh}\big((1,-1,2)\big)&=(0.76159416&, -0.76159416&,  0.96402758&)\\
u_{4..6} &=\text{tanh}(w_{4..6} \cdot U) &= \text{tanh}\big((5,0,-3)\big)&=(0.9999092&,   0.0&,         -0.99505475&)\\
u_{5..7} &=\text{tanh}(w_{5..7} \cdot U) &= \text{tanh}\big((0,-1,0)\big)&=(0.0&,         -0.76159416&,  0.0        &)\\
\end{split}
\end{equation}

\

\begin{equation}
\begin{split}
Y &=\text{max-pool}\big((u_{1..3},u_{2..4},u_{3..5},u_{4..6},u_{5..7})\big) \\
  &=(0.9999092,  0.99998771, 0.96402758)\\
\end{split}
\end{equation}

In [ ]:
import numpy as np

U = np.array([[-1, 1, 0],
              [1,1,0],
              [0,0,-1],
              [1,-1,-1],
              [-1,-1,1],
              [1,0,-1]])
W = np.array([[2,2,0,-2,0,1],
              [0,-2,0,1,-2,1],
              [0,1,-2,1,1,0],
              [-2,1,1,0,-1,1],
              [1,0,-1,1,1,1]])

H = np.matmul(W, U)
H1 = np.tanh(H)

print(H)
print(H1)
print('result: ', np.max(H1, axis=0))

[[-1  6  1]
 [ 2 -1 -4]
 [ 1 -1  2]
 [ 5  0 -3]
 [ 0 -1  0]]
[[-0.76159416  0.99998771  0.76159416]
 [ 0.96402758 -0.76159416 -0.9993293 ]
 [ 0.76159416 -0.76159416  0.96402758]
 [ 0.9999092   0.         -0.99505475]
 [ 0.         -0.76159416  0.        ]]
result:  [0.9999092  0.99998771 0.96402758]


# Recurrent Neural Networks
### Pregunta 4 (1 pt)
Usando los embeddings de dos dimensiones de la pregunta anteror, la oración `el fuego quema` la podemos representar por una secuencia de vectores $(\vec{x}_1,\vec{x}_2,\vec{x}_3)$, con $\vec{x}_i \in \mathbb{R}^{d_x}$ y $d_x=2$.

Tenemos una red recurrente *Elman* definidad como: 
\begin{equation}
\begin{split}
\vec{s}_i &= R_{SRNN}\left (\vec{x}_i, \vec{s}_{i-1}\right ) = g \left (\vec{s}_{i-1}W^s + \vec{x}_i W^x + \vec{b}\right ) \\
\vec{y}_i &= O_{SRNN}\left(\vec{s}_i\right) = \vec{s}_i \\
\end{split}
\end{equation}
donde
\begin{equation}
\vec{s}_i, \vec{y}_i \in \mathbb{R}^{d_s}, \quad W^x \in \mathbb{R}^{d_x \times d_s}, \quad W^s \in \mathbb{R}^{d_s \times d_s}, \quad \vec{b} \in \mathbb{R}^{d_s},
\end{equation}
y los vectores de estado $s_i$ son de tres dimensiones, $ds= 3$.

Sea
\begin{equation}
\begin{split}
\vec{s}_0 &= [0,0,0]\\
W^x &= \begin{pmatrix}
0 &  0 & 1\\
1 & -1 & 0
\end{pmatrix} \\
W^s &= \begin{pmatrix}
1 & 0 &  1\\
0 & 1 & -1\\
1 & 1 &  1
\end{pmatrix} \\
\vec{b} &= [0, 0, 0] \\
g(x) &= ReLu(x) = max(0, x)
\end{split}
\end{equation}

<br>

Calcule manualmente los valores de los vectores $\vec{s}_1, \vec{s}_2,\vec{s}_3$ y de $\vec{y}_1, \vec{y}_2,\vec{y}_3$.

**Respuesta**

\begin{split}
    \vec{s}_1 &= \text{ReLu}(\vec{s_0}W^s + \vec{x_0}W^x+\vec{b}) \\
              &= \text{ReLu}([0,0,0]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [1,0]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix} + [0,0,0]) \\
              &= \text{ReLu}([0,0,1]) \\
              &= [0,0,1]
\end{split}

\

\begin{split}
    \vec{s}_2 &= \text{ReLu}(\vec{s_1}W^s + \vec{x_2}W^x+\vec{b}) \\
              &= \text{ReLu}([0,0,1]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [-1,1]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix}+[0,0,0]) \\ 
              &= \text{ReLu}([2,0,0]) \\
              &= [2,0,0] \\
\end{split}

\

\begin{split}
    \vec{s}_3 &= \text{ReLu}(\vec{s_2}W^s + \vec{x_3}W^x+\vec{b}) \\
              &= \text{ReLu}([2,0,0]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [1,1]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix}+[0,0,0])  \\
              &= \text{ReLu}([3,-1,3]) \\
              &= [3,0,3]
\end{split}

In [ ]:
import numpy as np
x  = np.array([[1,0], [-1,1], [1,1]])
s = np.array([0,0,0])
Ws = np.array([[1,0,1],[0,1,-1],[1,1,1]])
Wx = np.array([[0,0,1],[1,-1,0]])
b = np.array([0,0,0])
for xi in x: 
  print('\nstep for: ', xi)
  print(np.matmul(s,Ws))
  print(np.matmul(xi,Wx))
  s = np.matmul(s,Ws) + np.matmul(xi,Wx) + b
  print(s)


step for:  [1 0]
[0 0 0]
[0 0 1]
[0 0 1]

step for:  [-1  1]
[1 1 1]
[ 1 -1 -1]
[2 0 0]

step for:  [1 1]
[2 0 2]
[ 1 -1  1]
[ 3 -1  3]


### Pregunta 5 (0.5 pts)
¿De qué forma las RNN y las CNN logran aprender representaciones específicas
para la tarea objetivo? Compare la forma en que las RNN y las CNN aprenden con los modelos que usan *features* diseñadas manualmente.

**Respuesta**

Las RNN preservan la estructura a lo largo de la sequencia, codificando los vectores de la secuencia (embeddings) en un solo vector. En el caso de las tareas de sequence labeling, podemos usar los vectores de salida temporales (para cada uno de las posibles subsecuencias prefijo del texto), pasándolos por un modelo que los clasifique según el label.

Las RNN y las CNN no necesitan que se diseñen los features manualmente. Ellas son capaces de aprender los features directamente a partir de las propiedades estadísticas de la secuencia.

# Redes neuronales con PyTorch
### Pregunta 6 (2 pts)
En esta parte van a tener que implementar una red neuronal Feed Forward. Además, deberán entrenar el modelo usando uno de los datasets de TorchText. En la sección de la respuesta hay un esqueleto de lo que deben hacer, deberán completar los metodos del modelo e implementar la parte asociada al entrenamiento. Como les mencionamos en la [Auxiliar 3](https://www.youtube.com/watch?v=r1pt9v_vuy8&list=PLwITEwTGVF6jXRu6l55W4OedqDiLgU9OM&index=2&t=5s), el proceso de entrenamiento es bastante estándar, así que se pueden guiar en gran medida por los ejemplos que ahí mostramos y los que vamos a ver en las próximas auxiliares.

#### 6.1 Capa Convolucional (Opcional)
Agregue a la arquitectura una capa convolucional. Para esto puede registrar el parametro $U$ en la red y realizar el computo de la convolución en el metodo forward de la red, o puede usar la clase [`torch.nn.Conv1d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html#conv1d) de `torch`.


In [ ]:
# %%capture
# Nos aseguramos que torchtext este en la ultima version
!pip install torch==1.8.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchtext==0.9.0

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |█████████████▌                  | 834.1 MB 1.4 MB/s eta 0:14:08tcmalloc: large alloc 1147494400 bytes == 0x5620cc43c000 @  0x7f7e6b107615 0x56209254c02c 0x56209262c17a 0x56209254ee4d 0x562092640c0d 0x5620925c30d8 0x5620925bdc35 0x56209255073a 0x5620925c2f40 0x5620925bdc35 0x56209255073a 0x5620925bf93b 0x562092641a56 0x5620925befb3 0x562092641a56 0x5620925befb3 0x562092641a56 0x5620925befb3 0x562092550b99 0x562092593e79 0x56209254f7b2 0x5620925c2e65 0x5620925bdc35 0x56209255073a 0x5620925bf93b 0x5620925bdc35 0x56209255073a 0x5620925beb0e 0x56209255065a 0x5620925bed67 0x5620925bdc35
     |█████████████████               | 1055.7 MB 1.2 MB/s eta 0:12:25tcmalloc: large alloc 1434370048 bytes == 0x562110a92000 @  0x7f7e6b107615 0x56209254c02c 0x56209262c17a 0x56209254ee4d 0x562092640c0d 0x5620925c30d8 0x5620925bdc35 0x56209255073a 0x5620925c2f40 0x5620925bdc35 0x56209255073a 0x5620925bf93b 0x562092641a56 0x5620925bef

In [ ]:
# Trabajaremos con el dataset AG_NEWS de torchtext
# https://pytorch.org/text/stable/datasets.html#ag-news
import os
import torch
from random import choice
from torchtext.datasets import AG_NEWS
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

os.makedirs("data", exist_ok=True)
train_dataset, test_dataset = AG_NEWS(root="data", split=('train', 'test'))
train_list = list(train_dataset)
test_list = list(test_dataset)

# Informacion relevante del dataset
tokenizer = get_tokenizer("basic_english")
vocab = build_vocab_from_iterator(tokenizer(x[1]) for x in train_list)
num_classes = 4

train.csv: 29.5MB [00:00, 90.7MB/s]
test.csv: 1.86MB [00:00, 26.0MB/s]                  
120000lines [00:03, 33396.20lines/s]


In [ ]:
# De aca para abajo viene su respuesta, completen las funciones en la red
# y luego entrenen el modelo y evaluenlo usando los dataset que acaban de
# cargar
import torch
import torch.nn as nn
from itertools import zip_longest

class CNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim=32, num_classes=10, 
                 use_cnn=False, cnn_pool_channels=24, cnn_kernel_size=3):
      super().__init__()
      self.use_cnn = use_cnn
      
      if use_cnn:
        # capa de embedding
        self.embedding = nn.Embedding(vocab_size, embed_dim)

        # capa de convolución
        self.conv = nn.Conv1d(
            in_channels=1,
            out_channels=cnn_pool_channels,
            kernel_size=cnn_kernel_size * embed_dim,
            stride=embed_dim,
        )

        fc_in_size = cnn_pool_channels
      else:
        # capa de embedding, en este caso usamos EmbeddingBag 
        # por lo que necesitaremos los offsets del batch en el forwards
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True)

        fc_in_size = embed_dim

      # capa lineal
      self.fc = nn.Linear(fc_in_size, num_classes)

      self.init_weights()

    def init_weights(self):
      initrange = 0.5
      self.embedding.weight.data.uniform_(-initrange, initrange)
      self.fc.weight.data.uniform_(-initrange, initrange)
      self.fc.bias.data.zero_()

    def forward(self, text, offsets):
      if self.use_cnn:
        # preparamos el input de la capa de embeddings a partir de text y offsets
        # (N x longest_text)
        text = torch.tensor(
            list(
                zip(
                    *zip_longest(
                        *([text[o:offsets[i+1]] for i, o in enumerate(offsets[:-1])] + [text[offsets[-1]:len(texts)]]), 
                        fillvalue=vocab["<pad>"]
                    )
                )
            )
        ).to(text.device)

        # (N x longest_text x embed_dim)
        h = self.embedding(text)

        # (N x pool_channels)
        h = h.view(h.size(0), 1, -1)
        h = torch.relu(self.conv(h))
        h = h.mean(dim=2)
      else:
        # (N x embed_dim)
        h = self.embedding(text, offsets)

      # (N x num_classes)
      return self.fc(h)

In [ ]:
# El resto de su respuesta
# Aca deben programar el entrenamiento de la red

import sys
from torch.optim import SGD, lr_scheduler
from torch.utils.data import DataLoader
from torch.autograd import Variable

def generate_batch(batch):
  label = torch.tensor([entry[0]-1 for entry in batch])
  texts = [tokenizer(entry[1]) for entry in batch]
  offsets = [0] + [len(text) for text in texts]
  offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)
  big_text = torch.cat([torch.tensor([vocab.stoi[t] for t in text]) for text in texts])
  return big_text, offsets, label

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

BATCH_SIZE = 16
TEST_BATCH_SIZE = BATCH_SIZE * 5
LR = 1e-1

model = CNNClassifier(len(vocab), num_classes=num_classes, use_cnn=True).to(device)
optimizer = SGD(model.parameters(), lr=LR)
criterion = nn.CrossEntropyLoss().to(device)
scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=[lambda epoch: .9 ** (epoch // 10)])

split_size = {'train': len(train_list), 'test': len(test_list)}

# train_dataset, test_dataset = AG_NEWS(root="data")
for epoch in range(1, 80):
  train_loader = DataLoader(train_list, batch_size=BATCH_SIZE, collate_fn=generate_batch)
  test_loader = DataLoader(test_list, batch_size=TEST_BATCH_SIZE, collate_fn=generate_batch)
  loaders = {'train': train_loader, 'test': test_loader}
  for phase in ['train', 'test']:
    if phase == 'train':
      model.train()
    else:
      model.eval()

    total_acc, total_loss = 0, 0
    for i, (texts, offsets, cls) in enumerate(loaders[phase]):
      texts = texts.to(device)
      offsets = offsets.to(device)
      cls = cls.to(device)

      optimizer.zero_grad()
      with torch.set_grad_enabled(phase == 'train'):
        output = model(texts, offsets)
        loss = criterion(output, cls)
        total_loss += loss.item()
        if phase == 'train':
          loss.backward()
          optimizer.step()
      
      acc = (output.argmax(1) == cls).sum().item()
      total_acc += acc

      sys.stdout.write('\rEpoch: {0:03d}\t Phase: {1} Iter: {2:03d}/{3:03d}\t iter-Acc: {4:.3f}%\t iter-Loss: {5:.3f}'.format(epoch, phase, i, len(loaders[phase]), acc/len(offsets)*100, loss.item()))

    if phase == 'train':
      scheduler.step()
    print('\n {0}\tAvg. Acc: {1:.3f}%\t Avg. Loss: {2:.3f}'.format(phase, total_acc/split_size[phase]*100, total_loss/split_size[phase]))

cuda
Epoch: 001	 Phase: train Iter: 7499/7500	 iter-Acc: 93.750%	 iter-Loss: 0.225
 train	Avg. Acc: 59.071%	 Avg. Loss: 0.059
Epoch: 001	 Phase: test Iter: 094/095	 iter-Acc: 81.250%	 iter-Loss: 0.439
 test	Avg. Acc: 79.224%	 Avg. Loss: 0.007
Epoch: 002	 Phase: train Iter: 7499/7500	 iter-Acc: 93.750%	 iter-Loss: 0.147
 train	Avg. Acc: 84.485%	 Avg. Loss: 0.028
Epoch: 002	 Phase: test Iter: 094/095	 iter-Acc: 88.750%	 iter-Loss: 0.309
 test	Avg. Acc: 85.368%	 Avg. Loss: 0.006
Epoch: 003	 Phase: train Iter: 7499/7500	 iter-Acc: 93.750%	 iter-Loss: 0.111
 train	Avg. Acc: 87.889%	 Avg. Loss: 0.023
Epoch: 003	 Phase: test Iter: 094/095	 iter-Acc: 91.250%	 iter-Loss: 0.279
 test	Avg. Acc: 87.092%	 Avg. Loss: 0.005
Epoch: 004	 Phase: train Iter: 7499/7500	 iter-Acc: 93.750%	 iter-Loss: 0.088
 train	Avg. Acc: 89.330%	 Avg. Loss: 0.020
Epoch: 004	 Phase: test Iter: 094/095	 iter-Acc: 91.250%	 iter-Loss: 0.268
 test	Avg. Acc: 88.303%	 Avg. Loss: 0.005
Epoch: 005	 Phase: train Iter: 7499/7500	 i