# **Tarea 4 - CC6205 Natural Language Processing 📚**

**Integrantes:**

**Fecha límite de entrega 📆:** Lunes 06 de junio.

**Tiempo estimado de dedicación:**

Bienvenid@s a la cuarta tarea del curso de Natural Language Processing (NLP).
En esta tarea estaremos tratando el problema de **tagging** (generación de secuencias de etiquetas del mismo largo que la secuencia de input), el uso de **Convolutional Neural Networks** y **Recurrent Neural Networks**, e implementaremos una red usando PyTorch.

Usen $\LaTeX$ para las fórmulas matemáticas. En la parte de programación pueden usar lo que quieran, pero la [Auxiliar 3](https://youtu.be/36WTXvg3zh0) les puede ser de *gran ayuda*.

**Instrucciones:**
- La tarea se realiza en grupos de **máximo** 2 personas. Puede ser invidivual pero no es recomendable.
- La entrega es a través de u-cursos a más tardar el día estipulado arriba. No se aceptan atrasos.
- El formato de entrega es este mismo Jupyter Notebook.
- Al momento de la revisión tu código será ejecutado. Por favor verifica que tu entrega no tenga errores de compilación.
- En el horario de auxiliar pueden realizar consultas acerca de la tarea a través del canal de Discord del curso.

Si aún no han visto las clases, se recomienda visitar los links de las referencias.

**Referencias:**

- [Tagging, and Hidden Markov Models ](http://www.cs.columbia.edu/~mcollins/cs4705-spring2019/slides/tagging.pdf) (slides by Michael Collins), [notes](http://www.cs.columbia.edu/~mcollins/hmms-spring2013.pdf), [video 1](https://youtu.be/-ngfOZz8yK0), [video 2](https://youtu.be/Tjgb-yQOg54), [video 3](https://youtu.be/aaa5Qoi8Vco), [video 4](https://youtu.be/4pKWIDkF_6Y)       
- [MEMMs and CRFs](https://github.com/dccuchile/CC6205/blob/master/slides/NLP-CRF.pdf): [notes 1](http://www.cs.columbia.edu/~mcollins/crf.pdf), [notes 2](http://www.cs.columbia.edu/~mcollins/fb.pdf), [video 1](https://youtu.be/qlI-4lSUDkg), [video 2](https://youtu.be/PLoLKQwkONw), [video 3](https://youtu.be/ZpUwDy6o28Y)
- [Convolutional Neural Networks](https://github.com/dccuchile/CC6205/blob/master/slides/NLP-CNN.pdf): [video](https://youtu.be/lLZW5Fn40r8)
- [Recurrent Neural Networks](https://github.com/dccuchile/CC6205/blob/master/slides/NLP-RNN.pdf): [video 1](https://youtu.be/BmhjUkzz3nk), [video 2](https://youtu.be/z43YFR1iIvk), [video 3](https://youtu.be/7L5JxQdwNJk)

# Hidden Markov Models (HMM), Maximum Entropy Markov Models (MEMM) and Conditional Random Field(CRF)

### Pregunta 1 (1 pt)
Para un problema de POS tagging se define el conjunto de etiquetas $S = \{ \text{DET}, \text{NOUN}, \text{VERB}, \text{ADP} \}$ y se tiene un Hidden Markov Model con los siguientes parámetros estimados a partir de un corpus de entrenamiento:

\begin{equation}
\begin{split}
q(\text{NOUN}| \text{ VERB}, \text{DET}) &= 0.3 \\
q(\text{NOUN}|\ w, \text{DET}) &= 0 \qquad \forall w \in S, w \neq \text{VERB} \\
q(\text{DET}| \text{ VERB}, \text{NOUN}) &= 0.4 \\
q(\text{DET}|\ w, \text{NOUN}) &= 0 \qquad \forall w \in S, w \neq \text{VERB} \\
e(the|\text{ DET}) &= 0.5 \\
e(pasta|\text{ NOUN}) &= 0.6
\end{split}
\end{equation}

Luego para la oración: `the man is pouring sauce on the pasta`, se tiene una tabla de programación dinámica con los siguientes valores:
\begin{equation}
\begin{split}
\pi(7,\text{DET},\text{DET})&=0.1\\
\pi(7,\text{NOUN},\text{DET})&=0.2\\
\pi(7,\text{VERB},\text{DET})&=0.01\\
\pi(7,\text{ADP},\text{DET})&=0.5
\end{split}
\end{equation}

Con esta información, calcule el valor de $\pi(8,\text{DET},\text{NOUN})$. Puede dejar el resultado expresado como una fracción.


**Respuesta**
\begin{equation}
\begin{split}
\pi(8,\text{DET},\text{NOUN}) &= \max_{w\in S_{6}} \big(\pi(7, w, \text{DET}) \times q(\text{NOUN}|w,\text{DET}) \times e(\text{pasta}|\text{NOUN})\big)\\
&= \pi(7, \text{VERB}, \text{DET}) \times q(\text{NOUN}|\text{VERB},\text{DET}) \times e(\text{pasta}|\text{NOUN})\\
&= 0.01 \times 0.3 \times 0.6 \\
&= 0.0018
\end{split}
\end{equation}


### Pregunta 2 (0.5 pts)
Comente  sobre las similitudes o diferencias entre los HMMs, MEMMs y CRFs. Para esto, responda las siguientes preguntas.

#### 2.1. ¿Para qué tipo de tarea sirven? Dé dos ejemplo de este tipo de tarea y descríbalos brevemente. (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.2. ¿Qué modelos usan features? ¿Qué ventajas conlleva esto? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.3. ¿Cómo maneja cada uno de los modelos las palabras con baja frecuencia en el set de train? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.4. ¿Qué le permite a los CRF realizar decisiones globales? ¿Qué diferencia con respecto a los MEMMs permite lograr esto? ¿Por qué los HMMs tampoco son capaces de tomar decisiones globales? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

#### 2.5 Dado una secuencia de $x_1, ..., x_m$ ¿Cuántas posibles secuencias de etiquetas se pueden generar para un conjunto de etiquetas $S$ con $|S|=k$ ? ¿Analizarlas todas sería computacionalmente tratable? (0.1 pts)

**Respuesta:** Escriba su respuesta aquí

**Respuestas**
#### Problemas para los que sirven:
Problemas que producen como salida una secuencia de etiquetas, a partir de una secuencia de entrada. Estos problemas con conocidos como *sequence labeling* y dos ejemplos de problemas de este tipo son:
- Named Entity Recognition (NER): Tiene como objetivo localizar y clasificar en categorías predefinidas, como personas, organizaciones, lugares, expresiones de tiempo y cantidades, las entidades encontradas en el texto de input.
- Part-of-Speech (POS) Tagging: El objetivo es generar un secuencia de etiquetas que representan la categoría gramatical de cada una de las palabras del texto de input.

#### Modelos que usan features, ventajas:
Los modelos que usan features son MEMMs y CRF. Son modelos discriminativos mientras que los HMMs son modelos generativos. Los modelos discriminativos modelan directamente la probabilidad condicional utilizando un modelo parametrizado, minetras que los generativos utilizan solo la probabilidad conjunta.

#### Manejo de las palabras con baja frecuencia:
En lose HMMs se reemplazan las palabras poco frecuentes por categorías. Para esto, se divide el vocabulario en dos subconjuntos mediante un umbral de frecuencia: uno con las palabras frecuentes y otro con las poco frecuentes. Luego se convierten las poco frecuentes a un conjunto fijo de categorías, por ejemplo, las fechas, los numeros y los nombres.
En la fase de testing, las palabras desconocidas las podemos llevar a estas categorias en vez de solo usar el token **unk**.
Esto trae como ventaja una mejora en las propiedades de generalizacion del modelo.

En los MEMMs lo que tenemos son funciones parametrizadas para los cuales se aprenden pesos. Dado esto, el input se trata como un vector de caracteristicas (features).
Los inputs de los MEMMs incluyen la etiqueta. Esto tiene como ventaja que perimite codificar relaciones más directas entre la etiqueta y el input.
Estas relaciones se determinan mediante el uso de $\phi(\cdot, \cdot)$

#### Decisiones globales de los CRFs, diferencias con respecto a los HMMs y MEMMs:
En los CRFs la normalización es global, mientras que en los MEMMs la normalización en local. Esto hace que entrenar una MEMMs es menos complicado que entrenar los CRFs.

La gran ventaja de CRFs sobre MEMMs es que puede resolver un problema que se llama label bias. Este problema se da porque para algunas configuraciones de las etiquetas las MEMMs pueden ignorar informacion importante del contexto al realizar decisiones independientes en cada paso. Esto puede probocar una asignación erronea de la etiqueta.

# Convolutional Neural Networks
### Pregunta 3 (1 pt)

Considere la frase $w_{1..7}=$ `El agua moja y el fuego quema` $=[El, agua, moja, y, el, fuego, quema]$.

La siguiente matriz de embeddings, donde la i-ésima fila corresponde al vector de embedding de la i-ésima palabra, ordenadas según aparecen en la frase. (vectores de largo 2).
\begin{equation}
E = \begin{pmatrix}
2 & 2\\
0 & -2\\
0 & 1\\
-2 & 1\\
1 & 0\\
-1 & 1\\
1 & 1
\end{pmatrix}
\end{equation}

Los siguientes 3 filtros
\begin{equation}
U = \begin{pmatrix}
-1 & 1 & 0\\
1 & 1 & 0\\
0 & 0 & -1\\
1 & -1 & -1\\
-1 & -1 & 1\\
1 & 0 & -1
\end{pmatrix}
\end{equation}

Y la función de activación
\begin{equation}
tanh = \frac{e^{2x} - 1}{e^{2x} + 1}
\end{equation}

Usando estos paramátros escriba los pasos para calcular la representación (vector) resultante de aplicar la operación de convolución (sin padding) + max pooling. ¿De qué tamaño sería la ventana que debemos usar?

**Respuesta**
Dado que la matriz de filtro tiene 6 filas y los embedigs son vectores de largo 2, concluimos que la ventana es de tamaño 3. Por tanto estamos usando n-gramas de 3 palabras.

\begin{equation}
\begin{split}
w_{1..3} &=[El, agua, moja] &= \big(2,2,0,-2,0,1\big)\\
w_{2..4} &=[agua, moja, y]  &= \big(0,-2,0,1,-2,1\big)\\
w_{3..5} &=[moja, y, el]    &= \big(0,1,-2,1,1,0\big)\\
w_{4..6} &=[y, el, fuego]   &= \big(-2,1,1,0,-1,1\big)\\
w_{5..7} &=[el, fuego, quema] &= \big(1,0,-1,1,1,1\big)\\
\end{split}
\end{equation}

\

\begin{equation}
\begin{split}
[[-1  6  1]
 [ 2 -1 -4]
 [ 1 -1  2]
 [ 5  0 -3]
 [ 0 -1  0]]
u_{1..3} &=\text{tanh}(w_{1..3} \cdot U) &= \text{tanh}\big((-1,6,1)\big)&=(-0.76159416&,  0.99998771&,  0.76159416&)\\
u_{2..4} &=\text{tanh}(w_{2..4} \cdot U) &= \text{tanh}\big((1,-1,-4)\big)&=(0.96402758&, -0.76159416&, -0.9993293&)\\
u_{3..5} &=\text{tanh}(w_{3..5} \cdot U) &= \text{tanh}\big((1,-1,2)\big)&=(0.76159416&, -0.76159416&,  0.96402758&)\\
u_{4..6} &=\text{tanh}(w_{4..6} \cdot U) &= \text{tanh}\big((5,0,-3)\big)&=(0.9999092&,   0.0&,         -0.99505475&)\\
u_{5..7} &=\text{tanh}(w_{5..7} \cdot U) &= \text{tanh}\big((0,-1,0)\big)&=(0.0&,         -0.76159416&,  0.0        &)\\
\end{split}
\end{equation}

\

\begin{equation}
\begin{split}
Y &=\text{max-pool}\big((u_{1..3},u_{2..4},u_{3..5},u_{4..6},u_{5..7})\big) \\
  &=(0.9999092,  0.99998771, 0.96402758)\\
\end{split}
\end{equation}

In [ ]:
import numpy as np

U = np.array([[-1, 1, 0],
              [1,1,0],
              [0,0,-1],
              [1,-1,-1],
              [-1,-1,1],
              [1,0,-1]])
W = np.array([[2,2,0,-2,0,1],
              [0,-2,0,1,-2,1],
              [0,1,-2,1,1,0],
              [-2,1,1,0,-1,1],
              [1,0,-1,1,1,1]])

H = np.matmul(W, U)
H1 = np.tanh(H)

print(H)
print(H1)
print('result: ', np.max(H1, axis=0))

[[-1  6  1]
 [ 2 -1 -4]
 [ 1 -1  2]
 [ 5  0 -3]
 [ 0 -1  0]]
[[-0.76159416  0.99998771  0.76159416]
 [ 0.96402758 -0.76159416 -0.9993293 ]
 [ 0.76159416 -0.76159416  0.96402758]
 [ 0.9999092   0.         -0.99505475]
 [ 0.         -0.76159416  0.        ]]
result:  [0.9999092  0.99998771 0.96402758]


# Recurrent Neural Networks
### Pregunta 4 (1 pt)
Usando los embeddings de dos dimensiones de la pregunta anteror, la oración `el fuego quema` la podemos representar por una secuencia de vectores $(\vec{x}_1,\vec{x}_2,\vec{x}_3)$, con $\vec{x}_i \in \mathbb{R}^{d_x}$ y $d_x=2$.

Tenemos una red recurrente *Elman* definidad como:
\begin{equation}
\begin{split}
\vec{s}_i &= R_{SRNN}\left (\vec{x}_i, \vec{s}_{i-1}\right ) = g \left (\vec{s}_{i-1}W^s + \vec{x}_i W^x + \vec{b}\right ) \\
\vec{y}_i &= O_{SRNN}\left(\vec{s}_i\right) = \vec{s}_i \\
\end{split}
\end{equation}
donde
\begin{equation}
\vec{s}_i, \vec{y}_i \in \mathbb{R}^{d_s}, \quad W^x \in \mathbb{R}^{d_x \times d_s}, \quad W^s \in \mathbb{R}^{d_s \times d_s}, \quad \vec{b} \in \mathbb{R}^{d_s},
\end{equation}
y los vectores de estado $s_i$ son de tres dimensiones, $ds= 3$.

Sea
\begin{equation}
\begin{split}
\vec{s}_0 &= [0,0,0]\\
W^x &= \begin{pmatrix}
0 &  0 & 1\\
1 & -1 & 0
\end{pmatrix} \\
W^s &= \begin{pmatrix}
1 & 0 &  1\\
0 & 1 & -1\\
1 & 1 &  1
\end{pmatrix} \\
\vec{b} &= [0, 0, 0] \\
g(x) &= ReLu(x) = max(0, x)
\end{split}
\end{equation}

<br>

Calcule manualmente los valores de los vectores $\vec{s}_1, \vec{s}_2,\vec{s}_3$ y de $\vec{y}_1, \vec{y}_2,\vec{y}_3$.

**Respuesta**

\begin{split}
    \vec{s}_1 &= \text{ReLu}(\vec{s_0}W^s + \vec{x_0}W^x+\vec{b}) \\
              &= \text{ReLu}([0,0,0]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [1,0]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix} + [0,0,0]) \\
              &= \text{ReLu}([0,0,1]) \\
              &= [0,0,1]
\end{split}

\

\begin{split}
    \vec{s}_2 &= \text{ReLu}(\vec{s_1}W^s + \vec{x_2}W^x+\vec{b}) \\
              &= \text{ReLu}([0,0,1]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [-1,1]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix}+[0,0,0]) \\
              &= \text{ReLu}([2,0,0]) \\
              &= [2,0,0] \\
\end{split}

\

\begin{split}
    \vec{s}_3 &= \text{ReLu}(\vec{s_2}W^s + \vec{x_3}W^x+\vec{b}) \\
              &= \text{ReLu}([2,0,0]
              \begin{pmatrix}
                1 & 0 &  1\\
                0 & 1 & -1\\
                1 & 1 &  1
              \end{pmatrix}   + [1,1]
              \begin{pmatrix}
                0 &  0 & 1\\
                1 & -1 & 0
              \end{pmatrix}+[0,0,0])  \\
              &= \text{ReLu}([3,-1,3]) \\
              &= [3,0,3]
\end{split}

In [ ]:
import numpy as np
x  = np.array([[1,0], [-1,1], [1,1]])
s = np.array([0,0,0])
Ws = np.array([[1,0,1],[0,1,-1],[1,1,1]])
Wx = np.array([[0,0,1],[1,-1,0]])
b = np.array([0,0,0])
for xi in x:
  print('\nstep for: ', xi)
  print(np.matmul(s,Ws))
  print(np.matmul(xi,Wx))
  s = np.matmul(s,Ws) + np.matmul(xi,Wx) + b
  print(s)


step for:  [1 0]
[0 0 0]
[0 0 1]
[0 0 1]

step for:  [-1  1]
[1 1 1]
[ 1 -1 -1]
[2 0 0]

step for:  [1 1]
[2 0 2]
[ 1 -1  1]
[ 3 -1  3]


### Pregunta 5 (0.5 pts)
¿De qué forma las RNN y las CNN logran aprender representaciones específicas
para la tarea objetivo? Compare la forma en que las RNN y las CNN aprenden con los modelos que usan *features* diseñadas manualmente.

**Respuesta**

Las RNN preservan la estructura a lo largo de la sequencia, codificando los vectores de la secuencia (embeddings) en un solo vector. En el caso de las tareas de sequence labeling, podemos usar los vectores de salida temporales (para cada uno de las posibles subsecuencias prefijo del texto), pasándolos por un modelo que los clasifique según el label.

Las RNN y las CNN no necesitan que se diseñen los features manualmente. Ellas son capaces de aprender los features directamente a partir de las propiedades estadísticas de la secuencia.

# Pregunta 6: Redes Neuronales con Pytorch (3 puntos) 💬

<center>
<img src="https://www.anda.cl/wp-content/uploads/2021/03/0_5vNAtimPjYQr4W72.gif" alt="chatbot" width="400">
</center>

En esta sección de la tarea deberán implementar un Chatbot que sea capaz de generar una conversación *“básica”* utilizando un dataset de *Star Wars*. **El objetivo** de esta pregunta es que puedan aplicar lo aprendido sobre redes neuronales utilizando Pytorch en un ejemplo práctico.  Durante el desarrollo, se espera que puedan diseñar un bot (que tendrá por atrás un clasificador) que sea capaz de clasificar diferentes etiquetas, cosa que una vez identificada la etiqueta entregue una respuesta acorde a lo preguntado.

**Aviso:** Antes de comenzar con una descripción mas profunda de esta sección, les recomendamos que visualicen y se familiaricen con el dataset entregado, de esta forma comprenderán mejor la descripción del enunciado (aquí una pequeña ayudita 🆘).

In [ ]:
import pandas as pd

example_data = pd.read_json('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/star_wars_chatbot.json')
print("Cantidad de tags: ", example_data['intents'].shape[0])

Cantidad de tags:  16


A continuación, ejemplos del contenido del primer registro:

In [ ]:
example_data['intents'][0]['patterns']

['Hi',
 'Hey',
 'How are you',
 'Is anyone there?',
 'Hello',
 'Good day',
 "What's up",
 'Yo!',
 'Howdy',
 'Nice to meet you.']

In [ ]:
example_data['intents'][0]['responses']

['Hey',
 'Hello, thanks for visiting.',
 'Hi there, what can I do for you?',
 'Hi there, how can I help?',
 'Hello, there.',
 'Hello Dear',
 'Ooooo Hello, looking for someone or something?',
 'Yes, I am here.',
 'Listening carefully.',
 'Ok, I am with you.']

In [ ]:
example_data['intents'][0]['tag']

'greeting'

Del dataset cargado podemos notar que este viene en un formato `JSON`, por lo que sus datos están almacenados en diccionarios. Las llaves de los diccionarios no son aleatorias y estos nos sirven para identificar puntos relevantes en el desarrollo del bot. A continuación, se realiza una pequeña descripción de las llaves:

- `patterns`: Almacena los patrones con los que entrenaremos el modelo 😮, en otras palabras, es el corpus de entrenamiento que contiene solo preguntas o expresiones que deberá responder el bot.
- `responses`: Son las respuestas 🙋 relacionadas a los `patterns`, estas las utilizaremos en una etapa posterior a la clasificación, para dar una respuesta aleatoría al usuario.
- `tag`: Son las labels con las que entrenaremos nuestro modelo 💻.

En síntesis, las `keys` relevantes para el entrenamiento de nuestra red neuronal serán `patterns` (corpus) y `tag` (etiquetas).

#### Explicación de la tarea a realizar:

**Explicación de la tarea a realizar**: Implemente una Class llamada `CNNClassifier` que sea capaz de entrenar un modelo de texto a través de una red neuronal Feed Forward y una arquitectura convolucional (CNN 1D) [`torch.nn.Conv1d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html#conv1d) . Para el diseño de las redes tienen completa libertad, pero se le aconseja que se guíen de la última auxiliar para la construcción. Es **importantísimo** que el modelo a crear posea una capa de `Embedding` que se genere en base al entrenamiento del modelo. Creado el modelo, construya una función batch para cargar los datos de entrenamiento del modelo.

Construido el modelo, compare los resultados obtenidos para una red feed forward y una cnn. Para la comprobación de sus resultados ejecute el chatbot y pruebelo, ¿qué configuración tiene mejores resultados?, ¿a qué se deberan estos resultados?

Ojo que un ejemplo de prueba con el chatbot puede ser (agregue mas preguntas ud):

```
Let's chat! (type 'finish_chat' to finish the chat)
You: hi
GA-97: Yes, I am here.
You: can you tell me a joke?
GA-97: Have you tried the gluten-free Wookiee treats? No, but I heard they are a little Chewy.
```


**Igual [mucho texto](https://i0.wp.com/elgeneracionalpost.com/wp-content/uploads/2020/07/mucho-texto.jpg?fit=1280%2C720&ssl=1).... En resumen, ¿Qué se solicita?:**

- [ ] Diseñar una red neuronal Feed Forward.
- [ ] Diseñar un red convolucional.
- [ ] Crear el método forward de la clase `CNNClassifier`.
- [ ] Crear la función BATCH.
- [ ] Probar el modelo y comparar los resultados obtenidos con la red Feed Forward y la red CNN. Comente sus resultados de forma cualitativa, señalando con qué tipo de red obtuvo mejores resultados con el chatbot.

**Nota-1:** El modelo creado debe tener la opción de entrenar a traves de una feed forward y una CNN. Esto no significa que entrenará una FF y una CN, el modelo deberá recibir un booleano que especifique que tipo de red utilizará.

**Nota-2:** El dataset se descargará automáticamente en la sección `Carga de Dataset 📚`, no os preocupéis.

#### Pasemos al Código 🦾

Esqueleto propuesto (se **RECOMIENDA** que cambien **SOLO** la red neuronal y la función Batch) 🦴:

##### Instalamos librerias necesarias e importamos 😀

In [ ]:
%%capture
!pip install torch==1.8.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchtext==0.9.0

In [ ]:
import os
import sys
import json
import torch
import random
from random import choice
from torchtext.datasets import AG_NEWS
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from torch.optim import SGD, lr_scheduler
from torch.utils.data import DataLoader
from torch.autograd import Variable

from itertools import zip_longest

import plotly.express as px

import numpy as np
import nltk
from nltk.stem.porter import PorterStemmer

##### Carga de Dataset 📚

In [ ]:
# we obtain the dataset
!wget 'https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/star_wars_chatbot.json'

--2023-06-02 15:57:18--  https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/star_wars_chatbot.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14469 (14K) [text/plain]
Saving to: ‘star_wars_chatbot.json’

star_wars_chatbot.j 100%[===================>]  14.13K  --.-KB/s    in 0s      

2023-06-02 15:57:18 (89.4 MB/s) - ‘star_wars_chatbot.json’ saved [14469/14469]



In [ ]:
# Load the dataset using json
with open('star_wars_chatbot.json', 'r') as f:
    dataset = json.load(f)

# Create a vocab with the dataset and get the number of classes that have
tokenizer = get_tokenizer("basic_english")
vocab = build_vocab_from_iterator(tokenizer(x) for list_words in dataset['intents'] for x in list_words['patterns'])
num_classes = len(dataset['intents'])

# Define a list with the labels
labels = sorted(set([tag for tag in [intents['tag'] for intents in dataset['intents']]]))
# Define a train_list where we can find the info in the format: [(tag_0, text_0)...,(tag_n-1, text_n-1)]
train_list = [(labels.index(intents['tag']), text) for intents in dataset['intents'] for text in intents['patterns']]

##### Creación del modelo (2 puntos en total)

In [ ]:
import torch.nn.functional as F

class CNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim=32, num_classes=10,
                 use_cnn=False, cnn_pool_channels=24, cnn_kernel_size=3):
      super().__init__()
      self.use_cnn = use_cnn

      if use_cnn:
        # capa de embedding
        self.embedding = nn.Embedding(vocab_size, embed_dim)

        # capa de convolución
        self.conv = nn.Conv1d(
            in_channels=1,
            out_channels=cnn_pool_channels,
            kernel_size=cnn_kernel_size * embed_dim,
            stride=embed_dim,
        )

        fc_in_size = cnn_pool_channels
      else:
        # capa de embedding, en este caso usamos EmbeddingBag
        # por lo que necesitaremos los offsets del batch en el forwards
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True)

        fc_in_size = embed_dim

      # capa lineal
      self.fc = nn.Linear(fc_in_size, num_classes)

      self.init_weights()

    def init_weights(self):
      initrange = 0.5
      self.embedding.weight.data.uniform_(-initrange, initrange)
      self.fc.weight.data.uniform_(-initrange, initrange)
      self.fc.bias.data.zero_()

    def forward(self, text, offsets):
      if self.use_cnn:
        # preparamos el input de la capa de embeddings a partir de text y offsets
        # (N x longest_text)
        text = torch.tensor(
            list(
                zip(
                    *zip_longest(
                        *([text[o:offsets[i+1]] for i, o in enumerate(offsets[:-1])] + [text[offsets[-1]:len(texts)]]),
                        fillvalue=vocab["<pad>"]
                    )
                )
            )
        ).to(text.device)

        # (N x longest_text x embed_dim)
        h = self.embedding(text)

        # (N x pool_channels)
        h = h.view(h.size(0), 1, -1)
        h = torch.relu(self.conv(h))
        h = h.mean(dim=2)
      else:
        # (N x embed_dim)
        h = self.embedding(text, offsets)

      # (N x num_classes)
      output = self.fc(h)
      return F.log_softmax(output, dim=1)

In [ ]:
# Construya el modelo
import torch.nn.functional as F
class CNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim=32, num_classes=16,
                 use_cnn=False, cnn_pool_channels=24, cnn_kernel_size=3):
      super().__init__()

      self.use_cnn = use_cnn
      # capa de embedding
      #self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, mode="mean")
      self.embedding = nn.Embedding(vocab_size, embed_dim, 1)
      if use_cnn:
        # capa de convolucion
        self.conv = nn.Conv1d(
            in_channels=1,
            out_channels=cnn_pool_channels,
            kernel_size=cnn_kernel_size * embed_dim,
            stride=embed_dim,
        )
        self.pool = nn.MaxPool1d(3)
        #fc_in_size = cnn_pool_channels
        self.conv2 = nn.Conv1d(cnn_pool_channels, cnn_pool_channels, 1)
        fc_in_size = cnn_pool_channels
      else:
        fc_in_size = embed_dim
      # capas lineales
      self.fc1 = nn.Linear(fc_in_size, 42)
      self.fc2 = nn.Linear(42, num_classes)

      self.init_weights()


    def init_weights(self):
      # Esto puede ser util para inicializar los pesos
      initrange = 0.5
      self.embedding.weight.data.uniform_(-initrange, initrange)
      self.fc1.weight.data.uniform_(-initrange, initrange)
      self.fc1.bias.data.zero_()
      self.fc2.weight.data.uniform_(-initrange, initrange)
      self.fc2.bias.data.zero_()

    def forward(self, text, offsets):
      text = torch.tensor(
          list(
              zip(
                  *zip_longest(
                      *([text[o:offsets[i+1]] for i, o in enumerate(offsets[:-1])] + [text[offsets[-1]:len(texts)]]),
                      fillvalue=vocab["<pad>"]
                  )
              )
          )
      ).to(text.device)
      h = self.embedding(text)
      #h = h.mean(dim=1)
      if self.use_cnn:
        h = h.view(h.size(0), 1, -1)
        h = torch.relu(self.conv(h))
        h = self.pool(h)
        h = torch.relu(self.conv2(h))
        h = h.mean(dim=2)
      else:
        h = h.mean(dim=1)
      h = F.relu(self.fc1(h))
      h = self.fc2(h)
      return h

##### Función Batch 👷 (0,5 puntos)

In [ ]:
# Define a function to load the batch.
def generate_batch(batch):
  label = torch.tensor([entry[0] for entry in batch])
  texts = [tokenizer(entry[1]) for entry in batch]
  offsets = [0] + [len(text) for text in texts]
  offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)
  big_text = torch.cat([torch.tensor([vocab.stoi[t] for t in text]) for text in texts])
  return big_text, offsets, label

##### Entrenamiento 🥊

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"GPU is avaible: {device}")

# Define the different inputs in our model
num_epochs = 5
BATCH_SIZE = 16
LR = 1e-1
INPUT_SIZE = len(vocab)
OUTPUT_SIZE = num_classes
USE_CNN = False

# Define model, optimizer, loss and scheduler (Q: ¿What is it?)
model = CNNClassifier(INPUT_SIZE, num_classes=OUTPUT_SIZE, use_cnn=USE_CNN).to(device)
optimizer = SGD(model.parameters(), lr=LR)
criterion = nn.CrossEntropyLoss().to(device)
scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=[lambda epoch: .9 ** (epoch // 10)])

print(f'train: {len(train_list)} elements')

# We train the model using the intents
loss_list= []
for epoch in range(1, num_epochs):
  train_loader = DataLoader(train_list, batch_size=BATCH_SIZE, collate_fn=generate_batch)
  model.train()
  total_loss = 0
  for i, (texts, offsets, cls) in enumerate(train_loader):
    texts = texts.to(device)
    offsets = offsets.to(device)
    cls = cls.to(device)
    optimizer.zero_grad()
    output = model(texts, offsets)
    loss = criterion(output, cls)
    total_loss += loss.item()
    loss.backward()
    optimizer.step()

  loss_list.append(loss.item())
  sys.stdout.write('\rEpoch: {0:03d} \t iter-Loss: {1:.3f}'.format(epoch+1, loss.item()))

print(f'final loss: {loss.item():.4f}')

GPU is avaible: cuda
train: 97 elements


AttributeError: ignored

In [ ]:
# Plot de Entrenamiento
import plotly.express as px
fig = px.line(y=loss_list, x=np.arange(1,num_epochs), title="Training Loss")
fig.update_layout(
    xaxis_title="Epochs",
    yaxis_title="Loss"
    )

##### A probar! 🧪

In [ ]:
device

device(type='cuda')

In [ ]:
# This is working?, Try the next example!
qText = "'Do you know any joke?'" # this must classify the label "funny"

X = torch.tensor([vocab.stoi[t] for t in tokenizer(qText)]).to(device)

model.eval()
output = model(X, torch.tensor([0], dtype=torch.long).to(device))
_, predicted = torch.max(output, dim=1)
labels[predicted]

'funny'

Ya pero prometiste hacer un chatbot, no una simple clasificación....

##### Guardamos modelo 🦺 (opcional)

In [ ]:
# We save de model using pytorch (this is optional, just to learn how to do this in pytorch)
data = {
"model_state": model.state_dict(),
"input_size": INPUT_SIZE,
"output_size": OUTPUT_SIZE,
"use_cnn": USE_CNN,
"labels": labels
        }

FILE = "data.pth"
torch.save(data, FILE)

print(f'training complete. file saved to {FILE}')

training complete. file saved to data.pth


##### Chatbot 💬

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

with open('star_wars_chatbot.json', 'r') as json_data:
    intents = json.load(json_data)

FILE = "data.pth"
data = torch.load(FILE)

INPUT_SIZE = data["input_size"]
OUTPUT_SIZE = data["output_size"]
USE_CNN = data["use_cnn"]
labels = data['labels']
model_state = data["model_state"]

model = CNNClassifier(INPUT_SIZE, num_classes=OUTPUT_SIZE, use_cnn=USE_CNN).to(device)
model.load_state_dict(model_state)
model.eval()

# Dictionary with the answers
responses = {key['tag']: key['responses'] for key in dataset['intents']}

bot_name = "GA-97"
print("Let's chat! (type 'finish_chat' to finish the chat)")
while True:
    q_text = input("You: ")
    q_text = "'"+q_text+"'"
    if q_text == "'finish_chat'":
        break

    X = torch.tensor([vocab.stoi[t] for t in tokenizer(q_text)]).to(device)
    output = model(X, torch.tensor([0], dtype=torch.long).to(device))
    _, predicted = torch.max(output, dim=1)

    tag = labels[predicted.item()]

    probs = torch.softmax(output, dim=1)
    prob = probs[0][predicted.item()]
    if prob.item() > 0.50:
      print(f"{bot_name}: {random.choice(responses[tag])}")
    else:
      print(f"{bot_name}: My model can't understand you...")

FileNotFoundError: ignored

#### Comente los resultados aquí (0,5 puntos)

``Comente los resultados aquí``